### ISSUE TITLE
question about kanjilist.json file under data folder

### ISSUE THREAD

**Issue by TwoDeen** [gabor-kovacs/the-kanji-map#19]
A very useful project for Kanji enthusiasts. 
In the data folder, there is a file called `kanjilist.json` 
The contents have four fields k, r, m & g
I'm assuming k is for kanji-character, r is for reading(s) and m is for meaning(s)
What does `g` stand for?
Thank you
extract here
`{"k":"⺌","r":"","m":"","g":3}`

**Comment by gabor-kovacs** [comment]
Take a look at `preprocess/2_create_searchlist.ts` used to generate it.
`g` stands for group, where 1 = joyo, 2 = jinmeiyo, 3 = neither 
This is used for sorting the search results. The keys are abbrevated to reduce the file size since the whole thing is loaded client side to allow searching the kanji list (although I think most browsers send it gzipped anyways)
